version: '3'
services:
  noisebuster:
    build: .
    container_name: noisebuster
    volumes:
      - ./images:/images
      - ./config.json:/app/config.json
    devices:
      - "/dev/bus/usb:/dev/bus/usb"  # Necessary to access the USB device
    restart: unless-stopped
